---
title       : Banting Air Pullutant Index
subtitle    : Aug 2013 - Feb 2015
author      : Weixiang Lim
job         : 
framework   : io2012        # {io2012, html5slides, shower, dzslides, ...}
highlighter : highlight.js  # {highlight.js, prettify, highlight}
hitheme     : tomorrow      # 
widgets     : []            # {mathjax, quiz, bootstrap}
mode        : selfcontained # {standalone, draft}
knit        : slidify::knit2slides
---

## Introduction
Banting Air Pullutant Index app provides the hourly changes of the API reading in Banting, based on the selected Month and Year. It gives the trends prediction of the API of Banting. 

The data can be obtained from http://www.data.gov.my/, it's measured by the Malaysian Meteorological Department.

The data in this application only covered the measured API from August 2013 and February 2015.

---

## Data
```{r}
banting <- read.csv("API_Banting.csv")
str(banting)
```

---

## Shiny App
This shiny app can be viewed at the following link:

http://uueixiang.shinyapps.io/BantingAirPollutionIndex/

This application demonstrated the features in Shiny application that allows creation of interactive R programs embedded into web page.

1. The Select Box input is used to receive user action
2. Plot Output/Data Table Output is used to display the outcome of user selection.
3. The reactive output is displayed in the graph as a result of server processes.

Based on the outcome of the graph, we can observe that API readings usually peak around 3-4pm in the evening.

---

## Github Repo

The code for the shiny app can be obtained at the following github repo: 

http://github.com/uueixiang/DevelopingDataProducts

This repo also contains all the codes and data involved.
* README.md
* API_Banting data
* Shiny app code: ui.R and server.R
* Slidify Rmarkdown of this presentation


